Issue : Unable to get dumps
01org/satt pull request #2
Opened 2017-03-20 04:58 UTC by codernavi18

**Issue**   : Unable to get dumps  
              Error "cannot obtain sideband data"

**Fix**     : Added fix to correct the string parsing done in SATT
          without which SATT will generate wrong filenames and
          will fail to obtain the sideband data

**Test**    : Getting proper dumps with no errors

**Signed-off-by**: nkumarch <naveen.kumar.chaudhary@intel.com>

2017-03-20 07:47 UTC, storola commented on satt/common/targetos/os_android.py
> +		    line = line.strip();
Change Tabs to spaces for both lines and we are good to go.

2017-03-20 07:49 UTC, storola requested changes
Looks good but few tabs need to be changed to spaces.

2017-03-27 04:09 UTC, codernavi18 commented
@storola Made the suggested changes. Please check

2017-05-05 07:40 UTC, storola approved these changes

2017-05-30 14:03 UTC, merged